const main = document.getElementById('main')
const addUser = document.getElementById('add-user')
const double = document.getElementById('double')
const showMillie = document.getElementById('show-millionaires')
const  = document.getElementById('main')
const main = document.getElementById('main')