const main = document.getElementById('main')
const addUser = document.getElementById('add-user')
const double = document.getElementById('double')
const showMillie = document.getElementById('show-millionaires')
const sort = document.getElementById('sort')
const calculateWealthT = document.getElementById('main')